### PR TITLE
Update password reset email to use `get_username`.

### PR DESCRIPTION
**Pull request by maxpeterson**

### CODE REVIEW

**Comment by maxpeterson** [comment]
thanks @meshy - I was trying to figure out who if anyone else had write access.

**Comment by maxpeterson** [comment]
@meshy I just add you as a collaborator - let me know if you want / need different access to this or other incuna libraries

**Comment by meshy** [comment]
Welcome! Thanks for adding me -- nothing springs to mind for myself at the moment, but I think that @KevinEtienne would appreciate access to `pg-crypto-fields`. (Ref: https://github.com/incuna/django-pgcrypto-fields/issues/47)

**Comment by meshy** [comment]
Oh, that was daft of me -- I can see now that he already has a "Contributor" flag -- My bad!

**Pull request merged**
