### PR TITLE
Various Tidy Ups

### PR DESCRIPTION
**Pull request by ghickman**
This makes a few minor aesthetic changes to improve readability and quality.

### CODE REVIEW

**Comment by meshy** [comment]
Thanks, dude, this is a nice refactor.

Looking at it a little more closely, it doesn't look as though the `realm` argument is ever passed to `challenge`. Perhaps that should go too!

Do you fancy writing the changelog for 3.0.0?

**Comment by ghickman** [comment]
@meshy – removed the realm parameter. Do you want the changelog in this PR too?

**Comment by meshy** [comment]
Thanks! Yes, please!

**Comment by meshy** [comment]
:cake: :+1:

**Pull request merged**
