### PR TITLE
Add fr_LU

### PR DESCRIPTION
**Pull request by KevinEtienne**

### CODE REVIEW

**Comment by KevinEtienne** [comment]
@incuna/backend happy to merge?

**Comment by todd-dembrey** [comment]
HWTI

**Comment by KevinEtienne** [comment]
Thanks

**Comment by maxpeterson** [comment]
@KevinEtienne I thought this was going to be based on the `fr-be` one or we were going to use a `fr` version.

**Comment by KevinEtienne** [comment]
Yeah `fr` version is the best solution.

**Pull request merged**
