### PR TITLE
Mark string `You must be logged in to view this page.` as translatable. Also compile translations.

### PR DESCRIPTION
**Pull request by Minglee01**
@incuna/backend 

please review

mark string as translatable.

### CODE REVIEW

**Comment by adam-thomas** [comment]
This PR seems to do quite a bit more than its title would suggest? :)

**Comment by todd-dembrey** [comment]
FR_BE FR_LU translations were removed but it looks like it wasn't turned off in makefile.

https://github.com/incuna/incuna-auth/blob/a4cb6390a851b872e511ff13b4a054d4c3a7eafb/Makefile#L28

**Comment by Minglee01** [comment]
Question is why

**Comment by todd-dembrey** [comment]
https://github.com/incuna/incuna-auth/pull/59

**Comment by Minglee01** [comment]
@incuna/backend  bump new day

**Comment by adam-thomas** [comment]
:+1:

**Pull request merged**
